[Thu Jan 31 10:24:29.312129 2019] [php7:notice] [pid 19560] [client 192.168.34.180:55576] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:24:29.686641 2019] [php7:notice] [pid 19560] [client 192.168.34.180:55576] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:24:29.755871 2019] [php7:notice] [pid 19563] [client 192.168.34.180:55578] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:24:29.823749 2019] [php7:notice] [pid 19516] [client 192.168.34.180:55588] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:24:33.236536 2019] [php7:notice] [pid 19521] [client 192.168.34.180:55594] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:24:33.359323 2019] [php7:notice] [pid 19521] [client 192.168.34.180:55594] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:24:33.366300 2019] [php7:notice] [pid 19564] [client 192.168.34.180:55598] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:24:40.460101 2019] [php7:notice] [pid 19517] [client 192.168.34.180:55604] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:24:40.559380 2019] [php7:notice] [pid 19517] [client 192.168.34.180:55604] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:24:40.564766 2019] [php7:notice] [pid 19518] [client 192.168.34.180:55608] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:25:06.358016 2019] [php7:notice] [pid 19519] [client 192.168.34.180:55618] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:25:06.415822 2019] [php7:notice] [pid 19519] [client 192.168.34.180:55618] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:25:06.440440 2019] [php7:notice] [pid 19520] [client 192.168.34.180:55616] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 10:54:14.621419 2019] [php7:notice] [pid 19516] [client 127.0.0.1:53762] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}, referer: http://localhost/core/install.php?langcode=es&profile=standard
[Thu Jan 31 10:56:24.462505 2019] [php7:notice] [pid 19948] [client 127.0.0.1:53786] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:15:01.193991 2019] [php7:notice] [pid 20948] [client 127.0.0.1:54162] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:15:14.248049 2019] [php7:notice] [pid 20950] [client 127.0.0.1:54168] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:15:52.637174 2019] [php7:notice] [pid 20948] [client 127.0.0.1:54180] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:16:17.043294 2019] [php7:notice] [pid 20953] [client 127.0.0.1:54210] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:27:51.706068 2019] [php7:notice] [pid 20950] [client 127.0.0.1:54390] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:28:05.615141 2019] [php7:notice] [pid 21254] [client 127.0.0.1:54392] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:29:12.193477 2019] [php7:notice] [pid 21255] [client 127.0.0.1:54408] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:29:13.795104 2019] [php7:notice] [pid 21260] [client 127.0.0.1:54412] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:29:15.479518 2019] [php7:notice] [pid 21261] [client 127.0.0.1:54414] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:29:15.507896 2019] [php7:notice] [pid 21262] [client 127.0.0.1:54416] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:29:26.347255 2019] [php7:notice] [pid 21337] [client 127.0.0.1:54426] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:29:27.323587 2019] [php7:notice] [pid 21338] [client 127.0.0.1:54430] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:29:28.816293 2019] [php7:notice] [pid 21339] [client 127.0.0.1:54432] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:29:28.849551 2019] [php7:notice] [pid 21343] [client 127.0.0.1:54434] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:29:47.436404 2019] [php7:notice] [pid 21345] [client 127.0.0.1:54450] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:30:36.027587 2019] [php7:notice] [pid 21337] [client 127.0.0.1:54470] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:58:13.868810 2019] [php7:notice] [pid 21338] [client 192.168.34.180:58074] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 11:58:15.510426 2019] [php7:notice] [pid 21338] [client 192.168.34.180:58074] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 11:58:15.584480 2019] [php7:notice] [pid 21337] [client 192.168.34.180:58100] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 11:58:15.605119 2019] [php7:notice] [pid 21338] [client 192.168.34.180:58074] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 11:58:15.605203 2019] [php7:notice] [pid 21345] [client 192.168.34.180:58098] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 11:58:15.768255 2019] [php7:notice] [pid 21339] [client 192.168.34.180:58092] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 11:58:15.831487 2019] [php7:notice] [pid 21343] [client 192.168.34.180:58094] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 11:58:15.863235 2019] [php7:notice] [pid 21337] [client 192.168.34.180:58100] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 11:58:16.313243 2019] [php7:notice] [pid 21344] [client 192.168.34.180:58096] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 11:58:16.761357 2019] [php7:notice] [pid 21958] [client 127.0.0.1:55434] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:58:16.844002 2019] [php7:notice] [pid 21958] [client 127.0.0.1:55436] PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/drupar/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(512): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(867): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(465): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(655): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/drupar/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Thu Jan 31 11:58:31.041574 2019] [php7:notice] [pid 21962] [client 192.168.34.180:58128] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 11:58:31.227786 2019] [php7:notice] [pid 21962] [client 192.168.34.180:58128] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 11:58:31.234026 2019] [php7:notice] [pid 21963] [client 192.168.34.180:58134] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:03:51.788341 2019] [php7:notice] [pid 21965] [client 127.0.0.1:55746] Drupal\\Core\\Database\\DatabaseExceptionWrapper: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'field list': INSERT INTO {cache_bootstrap} (cid, expire, created, tags, checksum, data, serialized) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6) ON DUPLICATE KEY UPDATE cid = VALUES(cid), expire = VALUES(expire), created = VALUES(created), tags = VALUES(tags), checksum = VALUES(checksum), data = VALUES(data), serialized = VALUES(serialized); Array\n(\n    [:db_insert_placeholder_0] => state\n    [:db_insert_placeholder_1] => -1\n    [:db_insert_placeholder_2] => 1548947031.787\n    [:db_insert_placeholder_3] => \n    [:db_insert_placeholder_4] => 0\n    [:db_insert_placeholder_5] => a:1:{s:23:"system.maintenance_mode";N;}\n    [:db_insert_placeholder_6] => 1\n)\n in /var/www/drupar/core/lib/Drupal/Core/Cache/CacheCollector.php on line 265 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Connection.php(649): Drupal\\Core\\Database\\Connection->handleQueryException(Object(PDOException), 'INSERT INTO {ca...', Array, Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(87): Drupal\\Core\\Database\\Connection->query('INSERT INTO {ca...', Array, Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Query/Upsert.php(106): Drupal\\Core\\Database\\Driver\\mysql\\Connection->query('INSERT INTO {ca...', Array, Array)\n#3 /var/www/drupar/core/lib/Drupal/Core/Cache/DatabaseBackend.php(234): Drupal\\Core\\Database\\Query\\Upsert->execute()\n#4 /var/www/drupar/core/lib/Drupal/Core/Cache/DatabaseBackend.php(164): Drupal\\Core\\Cache\\DatabaseBackend->doSetMultiple(Array)\n#5 /var/www/drupar/core/lib/Drupal/Core/Cache/DatabaseBackend.php(152): Drupal\\Core\\Cache\\DatabaseBackend->setMultiple(Array)\n#6 /var/www/drupar/core/lib/Drupal/Core/Cache/CacheCollector.php(265): Drupal\\Core\\Cache\\DatabaseBackend->set('state', Array, -1, Array)\n#7 /var/www/drupar/core/lib/Drupal/Core/Cache/CacheCollector.php(326): Drupal\\Core\\Cache\\CacheCollector->updateCache()\n#8 /var/www/drupar/core/lib/Drupal/Core/EventSubscriber/KernelDestructionSubscriber.php(50): Drupal\\Core\\Cache\\CacheCollector->destruct()\n#9 /var/www/drupar/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): Drupal\\Core\\EventSubscriber\\KernelDestructionSubscriber->onKernelTerminate(Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent), 'kernel.terminat...', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#10 /var/www/drupar/vendor/symfony/http-kernel/HttpKernel.php(84): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('kernel.terminat...', Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent))\n#11 /var/www/drupar/vendor/stack/builder/src/Stack/StackedHttpKernel.php(32): Symfony\\Component\\HttpKernel\\HttpKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(634): Stack\\StackedHttpKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))\n#13 /var/www/drupar/index.php(22): Drupal\\Core\\DrupalKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))\n#14 {main}
[Thu Jan 31 12:04:13.339491 2019] [php7:notice] [pid 21964] [client 192.168.34.180:58440] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:04:13.880417 2019] [php7:notice] [pid 21964] [client 192.168.34.180:58440] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:04:14.714225 2019] [php7:notice] [pid 21964] [client 192.168.34.180:58440] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:04:14.715077 2019] [php7:notice] [pid 21343] [client 192.168.34.180:58454] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:04:14.716721 2019] [php7:notice] [pid 21337] [client 192.168.34.180:58456] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:04:15.123536 2019] [php7:notice] [pid 21964] [client 192.168.34.180:58440] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:04:15.319539 2019] [php7:notice] [pid 21337] [client 192.168.34.180:58456] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:04:18.655460 2019] [php7:notice] [pid 21964] [client 192.168.34.180:58440] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:04:20.734187 2019] [php7:notice] [pid 21964] [client 192.168.34.180:58440] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:04:21.694412 2019] [php7:notice] [pid 21964] [client 192.168.34.180:58440] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:04:22.015972 2019] [php7:notice] [pid 21964] [client 192.168.34.180:58440] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:09:39.705193 2019] [php7:notice] [pid 21338] [client 192.168.34.180:58582] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:09:40.196732 2019] [php7:notice] [pid 21338] [client 192.168.34.180:58582] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:26:26.259818 2019] [php7:notice] [pid 21962] [client 192.168.34.180:58922] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:26:26.613229 2019] [php7:notice] [pid 21962] [client 192.168.34.180:58922] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:26:28.926416 2019] [php7:notice] [pid 21962] [client 192.168.34.180:58922] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:26:29.479759 2019] [php7:notice] [pid 21962] [client 192.168.34.180:58922] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:26:35.623915 2019] [php7:notice] [pid 21963] [client 127.0.0.1:56274] Drupal\\Core\\Database\\DatabaseExceptionWrapper: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'field list': INSERT INTO {cache_bootstrap} (cid, expire, created, tags, checksum, data, serialized) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6) ON DUPLICATE KEY UPDATE cid = VALUES(cid), expire = VALUES(expire), created = VALUES(created), tags = VALUES(tags), checksum = VALUES(checksum), data = VALUES(data), serialized = VALUES(serialized); Array\n(\n    [:db_insert_placeholder_0] => state\n    [:db_insert_placeholder_1] => -1\n    [:db_insert_placeholder_2] => 1548948395.623\n    [:db_insert_placeholder_3] => \n    [:db_insert_placeholder_4] => 0\n    [:db_insert_placeholder_5] => a:1:{s:23:"system.maintenance_mode";N;}\n    [:db_insert_placeholder_6] => 1\n)\n in /var/www/drupar/core/lib/Drupal/Core/Cache/CacheCollector.php on line 265 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Connection.php(649): Drupal\\Core\\Database\\Connection->handleQueryException(Object(PDOException), 'INSERT INTO {ca...', Array, Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(87): Drupal\\Core\\Database\\Connection->query('INSERT INTO {ca...', Array, Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Query/Upsert.php(106): Drupal\\Core\\Database\\Driver\\mysql\\Connection->query('INSERT INTO {ca...', Array, Array)\n#3 /var/www/drupar/core/lib/Drupal/Core/Cache/DatabaseBackend.php(234): Drupal\\Core\\Database\\Query\\Upsert->execute()\n#4 /var/www/drupar/core/lib/Drupal/Core/Cache/DatabaseBackend.php(164): Drupal\\Core\\Cache\\DatabaseBackend->doSetMultiple(Array)\n#5 /var/www/drupar/core/lib/Drupal/Core/Cache/DatabaseBackend.php(152): Drupal\\Core\\Cache\\DatabaseBackend->setMultiple(Array)\n#6 /var/www/drupar/core/lib/Drupal/Core/Cache/CacheCollector.php(265): Drupal\\Core\\Cache\\DatabaseBackend->set('state', Array, -1, Array)\n#7 /var/www/drupar/core/lib/Drupal/Core/Cache/CacheCollector.php(326): Drupal\\Core\\Cache\\CacheCollector->updateCache()\n#8 /var/www/drupar/core/lib/Drupal/Core/EventSubscriber/KernelDestructionSubscriber.php(50): Drupal\\Core\\Cache\\CacheCollector->destruct()\n#9 /var/www/drupar/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): Drupal\\Core\\EventSubscriber\\KernelDestructionSubscriber->onKernelTerminate(Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent), 'kernel.terminat...', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#10 /var/www/drupar/vendor/symfony/http-kernel/HttpKernel.php(84): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('kernel.terminat...', Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent))\n#11 /var/www/drupar/vendor/stack/builder/src/Stack/StackedHttpKernel.php(32): Symfony\\Component\\HttpKernel\\HttpKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(634): Stack\\StackedHttpKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))\n#13 /var/www/drupar/index.php(22): Drupal\\Core\\DrupalKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))\n#14 {main}
[Thu Jan 31 12:26:35.967323 2019] [php7:notice] [pid 21963] [client 127.0.0.1:56274] Uncaught PHP Exception Drupal\\Core\\Database\\DatabaseExceptionWrapper: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'langcode' in 'where clause': SELECT url_alias.source AS source\nFROM \n{url_alias} url_alias\nWHERE (alias LIKE :db_condition_placeholder_0 ESCAPE '\\\\') AND (langcode IN (:db_condition_placeholder_1, :db_condition_placeholder_2))\nORDER BY langcode ASC, pid DESC; Array\n(\n    [:db_condition_placeholder_0] => /favicon.ico\n    [:db_condition_placeholder_1] => en\n    [:db_condition_placeholder_2] => und\n)\n" at /var/www/drupar/core/lib/Drupal/Core/Database/Connection.php line 685
[Thu Jan 31 12:26:36.016924 2019] [php7:notice] [pid 21963] [client 127.0.0.1:56274] Drupal\\Core\\Database\\DatabaseExceptionWrapper: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'field list': INSERT INTO {cache_bootstrap} (cid, expire, created, tags, checksum, data, serialized) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6) ON DUPLICATE KEY UPDATE cid = VALUES(cid), expire = VALUES(expire), created = VALUES(created), tags = VALUES(tags), checksum = VALUES(checksum), data = VALUES(data), serialized = VALUES(serialized); Array\n(\n    [:db_insert_placeholder_0] => state\n    [:db_insert_placeholder_1] => -1\n    [:db_insert_placeholder_2] => 1548948396.016\n    [:db_insert_placeholder_3] => \n    [:db_insert_placeholder_4] => 0\n    [:db_insert_placeholder_5] => a:1:{s:23:"system.maintenance_mode";N;}\n    [:db_insert_placeholder_6] => 1\n)\n in /var/www/drupar/core/lib/Drupal/Core/Cache/CacheCollector.php on line 265 #0 /var/www/drupar/core/lib/Drupal/Core/Database/Connection.php(649): Drupal\\Core\\Database\\Connection->handleQueryException(Object(PDOException), 'INSERT INTO {ca...', Array, Array)\n#1 /var/www/drupar/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(87): Drupal\\Core\\Database\\Connection->query('INSERT INTO {ca...', Array, Array)\n#2 /var/www/drupar/core/lib/Drupal/Core/Database/Query/Upsert.php(106): Drupal\\Core\\Database\\Driver\\mysql\\Connection->query('INSERT INTO {ca...', Array, Array)\n#3 /var/www/drupar/core/lib/Drupal/Core/Cache/DatabaseBackend.php(234): Drupal\\Core\\Database\\Query\\Upsert->execute()\n#4 /var/www/drupar/core/lib/Drupal/Core/Cache/DatabaseBackend.php(164): Drupal\\Core\\Cache\\DatabaseBackend->doSetMultiple(Array)\n#5 /var/www/drupar/core/lib/Drupal/Core/Cache/DatabaseBackend.php(152): Drupal\\Core\\Cache\\DatabaseBackend->setMultiple(Array)\n#6 /var/www/drupar/core/lib/Drupal/Core/Cache/CacheCollector.php(265): Drupal\\Core\\Cache\\DatabaseBackend->set('state', Array, -1, Array)\n#7 /var/www/drupar/core/lib/Drupal/Core/Cache/CacheCollector.php(326): Drupal\\Core\\Cache\\CacheCollector->updateCache()\n#8 /var/www/drupar/core/lib/Drupal/Core/EventSubscriber/KernelDestructionSubscriber.php(50): Drupal\\Core\\Cache\\CacheCollector->destruct()\n#9 /var/www/drupar/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): Drupal\\Core\\EventSubscriber\\KernelDestructionSubscriber->onKernelTerminate(Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent), 'kernel.terminat...', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#10 /var/www/drupar/vendor/symfony/http-kernel/HttpKernel.php(84): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('kernel.terminat...', Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent))\n#11 /var/www/drupar/vendor/stack/builder/src/Stack/StackedHttpKernel.php(32): Symfony\\Component\\HttpKernel\\HttpKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))\n#12 /var/www/drupar/core/lib/Drupal/Core/DrupalKernel.php(634): Stack\\StackedHttpKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))\n#13 /var/www/drupar/index.php(22): Drupal\\Core\\DrupalKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\HttpFoundation\\Response))\n#14 {main}
[Thu Jan 31 12:28:40.647470 2019] [php7:notice] [pid 21965] [client 192.168.34.180:58958] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
[Thu Jan 31 12:28:41.341919 2019] [php7:notice] [pid 21965] [client 192.168.34.180:58958] phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.
